# Generated by Django 3.0.1 on 2020-11-17 17:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0003_block'),
    ]

    operations = [
        migrations.AlterField(
            model_name='block',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False, unique=True),
        ),
    ]
