# Generated by Django 3.0.1 on 2020-11-17 17:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0004_auto_20201117_1719'),
    ]

    operations = [
        migrations.RenameField(
            model_name='block',
            old_name='user',
            new_name='chat_user',
        ),
    ]
